// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHyBYHW4EKdL5UK-P7-hEVTWxA53PhMRI',
    appId: '1:47025260456:web:00b0913b87910d26f43f9d',
    messagingSenderId: '47025260456',
    projectId: 'movie-c6e85',
    authDomain: 'movie-c6e85.firebaseapp.com',
    storageBucket: 'movie-c6e85.appspot.com',
    measurementId: 'G-X2EGP20NF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtC5MhSuYHa-ozQQ9ndkkKUDdJJpzYaFo',
    appId: '1:47025260456:android:dde5c15fd3270ec3f43f9d',
    messagingSenderId: '47025260456',
    projectId: 'movie-c6e85',
    storageBucket: 'movie-c6e85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCLS4c3si4G_12R1I7h-OkOAIR5GNATRU',
    appId: '1:47025260456:ios:c4e244344df66e74f43f9d',
    messagingSenderId: '47025260456',
    projectId: 'movie-c6e85',
    storageBucket: 'movie-c6e85.appspot.com',
    iosBundleId: 'com.moveie.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCLS4c3si4G_12R1I7h-OkOAIR5GNATRU',
    appId: '1:47025260456:ios:d218c685a6f34181f43f9d',
    messagingSenderId: '47025260456',
    projectId: 'movie-c6e85',
    storageBucket: 'movie-c6e85.appspot.com',
    iosBundleId: 'com.moveie.movieApp.RunnerTests',
  );
}
